all: assignment4_client.c
	gcc -o assignment4 assignment4_client.c -I/home/s22100584/ncurses/include/ncurses -L/home/s22100584/ncurses/lib -lncurses

//제 서버에서는 ncurses를 쓸때 이렇게 컴파일합니다!
//따로 ncurses를 깔아서 했습니다!

